# Generated by Django 6.0.4 on 2026-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bi', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=64)),
                ('senha_rec', models.CharField(max_length=64)),
                ('senha_rec2', models.CharField(max_length=64)),
                ('data_registro', models.DateField()),
            ],
        ),
    ]
