# Generated by Django 6.0.4 on 2026-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('B', 'bibliotecário'), ('A', 'Administrador')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
