# Generated by Django 6.0.4 on 2026-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('bi', models.CharField(max_length=14)),
                ('numero', models.IntegerField()),
                ('numero_alter', models.IntegerField()),
                ('estado', models.CharField(choices=[('A', 'ativo'), ('B', 'bloqueado')], max_length=1)),
            ],
        ),
    ]
